In [1]:
from cluster_methods.missingness_cluster import miscluster
from cluster_methods.projection_cluster import projcluster
from model.model import gsrs
from tools.tools import *
from sys import path
import pandas as pd
import numpy as np
import time

data = pd.read_csv('data/ratings.csv', header=None)

In [6]:
data_sample = data.sample(frac=0.1)
data_sample

           0     1    2
361806  2109  1907  3.0
470439  2896  3301  4.0
664090  3999  2513  3.0
340608  2010   603  1.0
355743  2084  1307  5.0
...      ...   ...  ...
370152  2164  1222  4.0
10234     73   208  3.0
66073    442  1370  4.0
424874  2576  2968  4.0
560793  3450  1473  3.0

[100021 rows x 3 columns]